language: ruby
rvm:
  - 2.4
services:
  - docker
before_install:
  - docker build -t exegete46/jekyll-base .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push exegete46/jekyll-base ;
    fi